"""Offline provider: runs the fleet with no API key and no network.

This exists so the product is demonstrable anywhere — a laptop on a plane, a
locked-down client network, a CI job. It is **not** a language model. It
composes each artifact from the deterministic profile and the agent's own spec,
so the numbers and findings are real even though the prose is templated.

Every artifact and every run it produces is labelled ``simulation`` so nobody
can mistake it for model output.
"""

from __future__ import annotations

from typing import Any

from app.domain.model import TokenUsage
from app.ports.llm_provider import LLMProvider, LLMRequest, LLMResponse

_BANNER = (
    "Generated by the ADE Studio offline simulation provider. Statistics are real "
    "(computed deterministically from the source); narrative is templated. Configure "
    "ADE_ANTHROPIC_API_KEY to run this agent on a Claude model."
)


class SimulationProvider(LLMProvider):
    name = "simulation"

    def available(self) -> bool:
        return True

    def complete(self, request: LLMRequest) -> LLMResponse:
        ctx = request.context
        agent: dict[str, Any] = dict(ctx.get("agent") or {})
        profiles: list[dict[str, Any]] = list(ctx.get("profiles") or [])
        datasets: list[str] = list(ctx.get("datasets") or [])
        artifacts: list[dict[str, Any]] = list(ctx.get("artifacts") or [])
        parameters: dict[str, Any] = dict(ctx.get("parameters") or {})
        files: list[dict[str, Any]] = list(ctx.get("files") or [])

        findings = _derive_findings(profiles) + _derive_file_findings(files)
        summary = _summary(agent, datasets, profiles, findings, files)

        payload: dict[str, Any] = {
            "summary": summary,
            "findings": [f["statement"] for f in findings] or [
                "No structural defects were detected in the sampled rows."
            ],
            "open_questions": [
                "Confirm the intended business grain for each selected object with its owner.",
                "Confirm whether the sampled window is representative of the full history.",
            ],
            "handoffs": _handoffs(agent),
            "artifacts": {},
        }

        for spec in artifacts:
            payload["artifacts"][spec["key"]] = _compose(
                spec, agent, datasets, profiles, findings, parameters, files
            )

        return LLMResponse(
            text=summary,
            data=payload,
            usage=TokenUsage(),
            provider=self.name,
            model_id="offline-simulation",
            stop_reason="end_turn",
        )


# --------------------------------------------------------------------------- #
# Grounding: findings derived from the real deterministic profile
# --------------------------------------------------------------------------- #


def _derive_findings(profiles: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Turn computed statistics into observations, with the number attached."""
    findings: list[dict[str, Any]] = []
    for profile in profiles:
        table = profile.get("table", "?")
        for column in profile.get("columns", []):
            name = column.get("column", "?")
            null_ratio = float(column.get("null_ratio") or 0.0)
            distinct_ratio = float(column.get("distinct_ratio") or 0.0)
            patterns = column.get("sample_patterns") or []

            if null_ratio >= 0.02:
                findings.append({
                    "table": table, "column": name, "category": "completeness",
                    "severity": "warn" if null_ratio < 0.2 else "error",
                    "statement": (
                        f"{table}.{name} is null in {null_ratio * 100:.2f}% of sampled rows."
                    ),
                    "evidence": f"null_ratio={null_ratio:.6f}",
                })
            if column.get("is_candidate_key"):
                findings.append({
                    "table": table, "column": name, "category": "uniqueness",
                    "severity": "info",
                    "statement": (
                        f"{table}.{name} is unique and non-null across every sampled row — "
                        "a primary key candidate."
                    ),
                    "evidence": f"distinct_ratio={distinct_ratio:.6f}, nulls=0",
                })
            for pattern in patterns:
                label = pattern.split(" ")[0]
                if label in {"email", "us_phone", "uuid"} and "/" in pattern:
                    matched, total = pattern.split("(")[1].rstrip(")").split("/")
                    if int(matched) < int(total):
                        findings.append({
                            "table": table, "column": name, "category": "validity",
                            "severity": "warn",
                            "statement": (
                                f"{table}.{name} is predominantly {label}-shaped but "
                                f"{int(total) - int(matched)} of {total} sampled values do not match."
                            ),
                            "evidence": pattern,
                        })
                if label in {"email", "us_phone"}:
                    findings.append({
                        "table": table, "column": name, "category": "classification",
                        "severity": "info",
                        "statement": (
                            f"{table}.{name} carries {label}-shaped values and is a candidate for "
                            "personal-data classification."
                        ),
                        "evidence": pattern,
                    })
            minimum = column.get("min_value")
            try:
                if minimum is not None and float(minimum) < 0 and "price" in name.lower():
                    findings.append({
                        "table": table, "column": name, "category": "range",
                        "severity": "error",
                        "statement": f"{table}.{name} contains negative values (min {minimum}).",
                        "evidence": f"min={minimum}",
                    })
            except (TypeError, ValueError):
                pass
    return findings


def _derive_file_findings(files: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Observations counted from file inputs.

    The file counterpart to ``_derive_findings``: everything asserted here was
    counted by the deterministic reader, so an offline run of a file-driven
    agent still reports real structure rather than an empty artifact. Most of
    the fleet reads files, so without this the offline mode would be blank for
    the majority of it.
    """
    findings: list[dict[str, Any]] = []
    writers: dict[str, list[str]] = {}

    for item in files:
        path = item.get("path") or item.get("file", "?")
        details = item.get("findings") or {}

        for entry in details.get("creates", []):
            findings.append({
                "table": entry["object"], "column": "", "category": "lineage",
                "severity": "info",
                "statement": (
                    f"{path} creates {entry['object']} ({entry['type']})."
                ),
                "evidence": f"parsed from {path}",
            })
        for entry in details.get("writes", []):
            writers.setdefault(entry["object"], []).append(path)
        reads = details.get("reads", [])
        if reads:
            findings.append({
                "table": "", "column": "", "category": "lineage",
                "severity": "info",
                "statement": (
                    f"{path} reads {len(reads)} object(s): "
                    + ", ".join(r["object"] for r in reads[:8])
                    + ("…" if len(reads) > 8 else "")
                ),
                "evidence": f"parsed from {path}",
            })

        if (count := details.get("field_count")) is not None:
            findings.append({
                "table": path, "column": "", "category": "structure",
                "severity": "info",
                "statement": f"{path} defines {count} field(s) in a fixed-width record layout.",
                "evidence": f"parsed from {path}",
            })
            if details.get("has_redefines"):
                findings.append({
                    "table": path, "column": "", "category": "structure",
                    "severity": "warn",
                    "statement": (
                        f"{path} uses REDEFINES: the same bytes carry different meanings "
                        "depending on context, which a naive column-per-field translation "
                        "would get wrong."
                    ),
                    "evidence": f"REDEFINES present in {path}",
                })

        for column in details.get("columns", []):
            nulls = int(column.get("null_count") or 0)
            sampled = int(column.get("sampled") or 0)
            if sampled and nulls:
                findings.append({
                    "table": path, "column": column["column"], "category": "completeness",
                    "severity": "warn" if nulls < sampled * 0.2 else "error",
                    "statement": (
                        f"{path}:{column['column']} is empty in {nulls} of {sampled} rows."
                    ),
                    "evidence": f"null_count={nulls}, sampled={sampled}",
                })
            if "sum" in column:
                findings.append({
                    "table": path, "column": column["column"], "category": "measure",
                    "severity": "info",
                    "statement": (
                        f"{path}:{column['column']} totals {column['sum']:,} across "
                        f"{sampled} rows (min {column['min']}, max {column['max']})."
                    ),
                    "evidence": f"sum={column['sum']}, mean={column.get('mean')}",
                })

    # An object written by more than one file is a genuine finding rather than
    # a formatting detail: two writers to one table is where silent divergence
    # starts.
    for obj, paths in writers.items():
        if len(set(paths)) > 1:
            findings.append({
                "table": obj, "column": "", "category": "lineage",
                "severity": "warn",
                "statement": (
                    f"{obj} is written by {len(set(paths))} separate files: "
                    + ", ".join(sorted(set(paths)))
                ),
                "evidence": "multiple writers parsed",
            })
    return findings


def _summary(
    agent: dict[str, Any],
    datasets: list[str],
    profiles: list[dict[str, Any]],
    findings: list[dict[str, Any]],
    files: list[dict[str, Any]] | None = None,
) -> str:
    files = files or []
    if files and not profiles:
        lines = sum(int(f.get('line_count') or 0) for f in files)
        languages = sorted({f.get('language', '?') for f in files})
        errors = sum(1 for f in findings if f['severity'] == 'error')
        return (
            f"{agent.get('name', 'Agent')} read {len(files)} file(s) "
            f"({', '.join(languages)}; {lines:,} lines) and recorded {len(findings)} "
            f"observation(s), {errors} of them errors."
        )
    scope = ", ".join(datasets) if datasets else "the registered estate"
    rows = sum(int(p.get("row_count") or 0) for p in profiles)
    columns = sum(len(p.get("columns") or []) for p in profiles)
    errors = sum(1 for f in findings if f["severity"] == "error")
    return (
        f"{agent.get('name', 'Agent')} examined {scope} "
        f"({len(profiles)} object(s), {columns} columns, {rows:,} rows). "
        f"{len(findings)} observation(s) recorded, {errors} at error severity."
    )


def _handoffs(agent: dict[str, Any]) -> list[dict[str, str]]:
    """Restate the agent's declared boundaries as explicit handoffs.

    Exclusions with no owning agent are human-owned by design and are not
    handoffs, so they are left out.
    """
    out: list[dict[str, str]] = []
    for goal in agent.get("non_goals", []):
        if not goal.get("owned_by"):
            continue
        out.append({
            "to_agent_id": str(goal["owned_by"]),
            "to_agent_name": str(goal.get("owner_name", "")),
            "reason": str(goal.get("exclusion", "")),
        })
        if len(out) == 3:
            break
    return out


# --------------------------------------------------------------------------- #
# Artifact composition
# --------------------------------------------------------------------------- #


def _compose(
    spec: dict[str, Any],
    agent: dict[str, Any],
    datasets: list[str],
    profiles: list[dict[str, Any]],
    findings: list[dict[str, Any]],
    parameters: dict[str, Any],
    files: list[dict[str, Any]] | None = None,
) -> Any:
    fmt = spec.get("format", "markdown")
    if fmt == "json":
        return _json_artifact(spec, agent, profiles, findings, files or [])
    if fmt == "yaml":
        return _yaml_artifact(spec, agent, datasets, findings, parameters)
    if fmt == "sql":
        return _sql_artifact(spec, agent, profiles)
    if fmt == "csv":
        return _csv_artifact(profiles)
    if fmt == "python":
        return _python_artifact(agent, datasets)
    return _markdown_artifact(spec, agent, datasets, profiles, findings, parameters)


def _json_artifact(
    spec: dict[str, Any],
    agent: dict[str, Any],
    profiles: list[dict[str, Any]],
    findings: list[dict[str, Any]],
    files: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    return {
        "generated_by": {"agent_id": agent.get("id"), "agent_name": agent.get("name")},
        "artifact": spec.get("key"),
        "note": _BANNER,
        "objects": [
            {
                "table": p.get("table"),
                "row_count": p.get("row_count"),
                "sampled_rows": p.get("sampled_rows"),
                "sample_strategy": p.get("sample_strategy"),
                "candidate_primary_keys": p.get("candidate_primary_keys"),
                "columns": p.get("columns"),
            }
            for p in profiles
        ],
        "sources": files or [],
        "observations": findings,
    }


def _yaml_artifact(
    spec: dict[str, Any],
    agent: dict[str, Any],
    datasets: list[str],
    findings: list[dict[str, Any]],
    parameters: dict[str, Any],
) -> dict[str, Any]:
    return {
        "apiVersion": "ade/v1",
        "kind": spec.get("title", "Artifact"),
        "metadata": {
            "produced_by": f"{agent.get('id')} — {agent.get('name')}",
            "scope": datasets,
            "parameters": parameters,
            "note": _BANNER,
        },
        "items": [
            {
                "id": f"{f['category']}-{index:03d}",
                "target": f"{f['table']}.{f['column']}",
                "category": f["category"],
                "severity": f["severity"],
                "statement": f["statement"],
                "evidence": f["evidence"],
                "status": "PROPOSED",
            }
            for index, f in enumerate(findings, start=1)
        ],
    }


def _sql_artifact(spec: dict[str, Any], agent: dict[str, Any], profiles: list[dict[str, Any]]) -> str:
    lines = [
        f"-- {spec.get('title')} — produced by agent {agent.get('id')} ({agent.get('name')})",
        f"-- {_BANNER}",
        "-- Review before execution. Nothing here has been run against a source.",
        "",
    ]
    for profile in profiles:
        table = str(profile.get("table", "target"))
        safe = table.replace(".", "_").lower()
        columns = profile.get("columns", [])
        lines.append(f"CREATE OR REPLACE VIEW stg_{safe} AS")
        lines.append("SELECT")
        projection = [f"    {c['column']}" for c in columns]
        lines.append(",\n".join(projection) if projection else "    *")
        lines.append(f"FROM {table};")
        lines.append("")
    return "\n".join(lines)


def _csv_artifact(profiles: list[dict[str, Any]]) -> str:
    rows = ["table,column,data_type,null_ratio,distinct_count,distinct_ratio,candidate_key"]
    for profile in profiles:
        for column in profile.get("columns", []):
            rows.append(
                f"{profile.get('table')},{column.get('column')},{column.get('data_type')},"
                f"{column.get('null_ratio')},{column.get('distinct_count')},"
                f"{column.get('distinct_ratio')},{column.get('is_candidate_key')}"
            )
    return "\n".join(rows)


def _python_artifact(agent: dict[str, Any], datasets: list[str]) -> str:
    return (
        f'"""Produced by agent {agent.get("id")} ({agent.get("name")}).\n\n{_BANNER}\n"""\n\n'
        f"SOURCES = {datasets!r}\n\n\n"
        "def transform(frame):\n"
        "    \"\"\"Review and complete before use.\"\"\"\n"
        "    return frame\n"
    )


def _markdown_artifact(
    spec: dict[str, Any],
    agent: dict[str, Any],
    datasets: list[str],
    profiles: list[dict[str, Any]],
    findings: list[dict[str, Any]],
    parameters: dict[str, Any],
) -> str:
    lines = [
        f"# {spec.get('title')}",
        "",
        f"> {_BANNER}",
        "",
        f"**Agent:** {agent.get('id')} — {agent.get('name')}  ",
        f"**Domain:** {agent.get('domain')}  ",
        f"**Autonomy tier:** {agent.get('tier')} ({agent.get('tier_name')})",
        "",
        "## Scope examined",
        "",
    ]
    lines += [f"- `{d}`" for d in datasets] or ["- The registered estate (no object selection)."]

    if profiles:
        lines += ["", "## Deterministic facts", "",
                  "| Object | Rows | Sampled | Columns | Key candidates |",
                  "|---|---:|---:|---:|---|"]
        for profile in profiles:
            keys = ", ".join(k["column"] for k in profile.get("candidate_primary_keys", [])) or "—"
            lines.append(
                f"| `{profile.get('table')}` | {profile.get('row_count'):,} | "
                f"{profile.get('sampled_rows')} | {len(profile.get('columns', []))} | {keys} |"
            )

    if findings:
        lines += ["", "## Observations", ""]
        for index, finding in enumerate(findings[:40], start=1):
            lines.append(
                f"{index}. **[{finding['severity'].upper()}] {finding['category']}** — "
                f"{finding['statement']}  \n   _Evidence:_ `{finding['evidence']}`"
            )
        if len(findings) > 40:
            lines.append(f"\n_{len(findings) - 40} further observations omitted from this view._")

    lines += ["", "## What this agent deliberately did not do", ""]
    for goal in agent.get("non_goals", []):
        lines.append(f"- {goal.get('exclusion')} → **{goal.get('owner_name')}**")

    if agent.get("acceptance_criteria"):
        lines += ["", "## Acceptance criteria checked", ""]
        lines += [f"- {c}" for c in agent["acceptance_criteria"]]

    if parameters:
        lines += ["", "## Run parameters", ""]
        lines += [f"- `{k}`: `{v}`" for k, v in parameters.items()]

    return "\n".join(lines) + "\n"
